# Investigación Profunda: Librería Pandas en Python
Integrantes del grupo: [Samira Sánchez]

Materia: [Lógica de programación]

Fecha: [28/07/2026]

In [ ]:
#1. ¿Qué es Pandas?
Pandas es una librería de código abierto (open-source) para el lenguaje de programación Python, desarrollada por Wes McKinney en 2008. Está especialmente diseñada para la manipulación, limpieza, transformación y análisis de datos estructurados (tabulares). Construida sobre NumPy, proporciona estructuras de datos flexibes y de alto rendimiento.

#2. ¿Para qué sirve?
- Carga de datos: Importa información desde múltiples formatos (CSV, Excel, SQL, JSON).
- Limpieza de datos: Manejo de valores nulos o faltantes (`NaN`), eliminación de duplicados y corrección de tipos de datos.
- Manipulación e Inspección: Filtrado, ordenamiento, combinación (`merge`, `join`) y reestructuración de tablas.
- Análisis Estadístico: Cálculo rápido de estadísticas descriptivas (media, mediana, desviación estándar).

#3. ¿Cómo se utiliza / implementa?
Pandas se instala usualmente con `pip install pandas` y se importa en el entorno de desarrollo con la siguiente convención estándar:
`import pandas as pd`

In [3]:
# ==========================================
# REQUISITO: Importación de la librería e inspección básica
# ==========================================
import pandas as pd
import numpy as np

print("Versión de Pandas instalada:", pd.__version__)

# Ejemplo de estructura Series (1D)
serie_ejemplo = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print("\n--- Ejemplo de Pandas Series ---")
print(serie_ejemplo)

# Ejemplo de estructura DataFrame (2D)
datos_basicos = {
    'Nombre': ['Ana', 'Carlos', 'Elena', 'David'],
    'Edad': [23, 30, 28, 35],
    'Ciudad': ['Quito', 'Guayaquil', 'Cuenca', 'Quito']
}
df_basico = pd.DataFrame(datos_basicos)
print("\n--- Ejemplo de Pandas DataFrame ---")
print(df_basico)

Versión de Pandas instalada: 2.2.2

--- Ejemplo de Pandas Series ---
a    10
b    20
c    30
d    40
e    50
dtype: int64

--- Ejemplo de Pandas DataFrame ---
   Nombre  Edad     Ciudad
0     Ana    23      Quito
1  Carlos    30  Guayaquil
2   Elena    28     Cuenca
3   David    35      Quito

In [ ]:
#4. Ejemplo Aplicado 1: Análisis Comercial y Agregación de Datos
Descripción del Algoritmo:
En este ejemplo creamos un conjunto de datos de ventas por vendedor, región y monto.
- Validaciones: Se verifica si existen valores de venta inválidos o nulos.
- Ciclos/Operaciones: Se utiliza la función `groupby()` de Pandas para agrupar los datos por región y calcular el total de ventas y el promedio por vendedor.

In [4]:
# ==========================================
# EJEMPLO APLICADO 1: Análisis de Ventas por Región
# ==========================================

# 1. Creación del Dataset de Ventas
data_ventas = {
    'Vendedor': ['Marta', 'Pedro', 'Juan', 'Sofia', 'Lucía', 'Diego'],
    'Region': ['Norte', 'Sur', 'Norte', 'Oeste', 'Sur', 'Oeste'],
    'Monto_Venta': [1200.50, 850.00, 1500.00, 2100.75, 950.25, 1800.00],
    'Unidades': [10, 5, 12, 15, 8, 14]
}

df_ventas = pd.DataFrame(data_ventas)

# 2. Validación de Datos (Comprobación de Nulos y Tipos)
print("--- VALIDACIÓN DE DATOS ---")
print("Valores nulos por columna:\n", df_ventas.isnull().sum())
print("\nInformación del DataFrame:")
df_ventas.info()

# 3. Procesamiento y Agregación (Simula filtrado y agrupamiento)
ventas_por_region = df_ventas.groupby('Region').agg(
    Total_Ventas=('Monto_Venta', 'sum'),
    Promedio_Venta=('Monto_Venta', 'mean'),
    Total_Unidades=('Unidades', 'sum')
).reset_index()

# 4. Ordenamiento por mayor total de ventas
ventas_por_region = ventas_por_region.sort_values(by='Total_Ventas', ascending=False)

print("\n--- RESULTADO DEL ANÁLISIS POR REGIÓN ---")
display(ventas_por_region)

--- VALIDACIÓN DE DATOS ---
Valores nulos por columna:
 Vendedor       0
Region         0
Monto_Venta    0
Unidades       0
dtype: int64

Información del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Vendedor     6 non-null      object
 1   Region       6 non-null      object
 2   Monto_Venta  6 non-null      float64
 3   Unidades     6 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

--- RESULTADO DEL ANÁLISIS POR REGIÓN ---

  Region  Total_Ventas  Promedio_Venta  Total_Unidades
1  Oeste       3900.75        1950.375              29
0  Norte       2700.50        1350.250              22
2    Sur       1800.25         900.125              13

In [ ]:

#5. Ejemplo Aplicado 2: Limpieza de Datos y Manejo de Valores Faltantes (Data Cleaning)
Descripción del Algoritmo:
Simula un proceso de limpieza de datos de rendimiento estudiantil donde existen valores nulos (`NaN`).
- Validaciones e Imputación: Se detectan los valores ausentes en las calificaciones.
- Tratamiento: Se imputan las calificaciones nulas utilizando la media del grupo mediante `fillna()`, y se crea una columna condicional indicando el estado del estudiante (Aprobado/Reprobado).

In [5]:
# ==========================================
# EJEMPLO APLICADO 2: Limpieza e Imputación de Datos
# ==========================================

# 1. Dataset con datos incompletos (NaN)
data_estudiantes = {
    'Estudiante': ['Luis', 'María', 'Jorge', 'Carmen', 'Paola', 'Andrés'],
    'Examen_1': [85.0, np.nan, 90.0, 60.0, np.nan, 75.0],
    'Examen_2': [88.0, 92.0, np.nan, 65.0, 70.0, 80.0],
    'Asistencia_Pct': [90, 95, 80, 70, 85, 90]
}

df_estudiantes = pd.DataFrame(data_estudiantes)
print("--- DATOS ORIGINALES CON VALORES NULOS ---")
display(df_estudiantes)

# 2. Imputación de valores faltantes con el promedio de cada examen
media_e1 = df_estudiantes['Examen_1'].mean()
media_e2 = df_estudiantes['Examen_2'].mean()

df_estudiantes['Examen_1'] = df_estudiantes['Examen_1'].fillna(media_e1)
df_estudiantes['Examen_2'] = df_estudiantes['Examen_2'].fillna(media_e2)

# 3. Cálculo del promedio final y validación de aprobación (>= 70)
df_estudiantes['Promedio_Final'] = (df_estudiantes['Examen_1'] + df_estudiantes['Examen_2']) / 2

# Condicional con np.where (Ciclo optimizado vectorizado)
df_estudiantes['Estado'] = np.where(df_estudiantes['Promedio_Final'] >= 70, 'Aprobado', 'Reprobado')

print("\n--- DATOS PROCESADOS Y LIMPIOS ---")
display(df_estudiantes)

--- DATOS ORIGINALES CON VALORES NULOS ---

  Estudiante  Examen_1  Examen_2  Asistencia_Pct
0       Luis      85.0      88.0              90
1      María       NaN      92.0              95
2      Jorge      90.0       NaN              80
3     Carmen      60.0      65.0              70
4      Paola       NaN      70.0              85
5     Andrés      75.0      80.0              90

--- DATOS PROCESADOS Y LIMPIOS ---

  Estudiante  Examen_1  Examen_2  Asistencia_Pct  Promedio_Final     Estado
0       Luis      85.0      88.0              90           86.50   Aprobado
1      María      77.5      92.0              95           84.75   Aprobado
2      Jorge      90.0      79.0              80           84.50   Aprobado
3     Carmen      60.0      65.0              70           62.50  Reprobado
4      Paola      77.5      70.0              85           73.75   Aprobado
5     Andrés      75.0      80.0              90           77.50   Aprobado